version: 2

project_name: hydectl

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    main: ./main.go
    binary: "hydectl"
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

    files:
      - LICENSE
      - README.md

  - id: binary
    format: binary
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"


nfpms:
  - vendor: "HyDE-Project"
    homepage: "https://github.com/HyDE-Project/hydectl"
    maintainer: "HyDE-Project <contact@hyde-project.org>"
    description: "HyDE CLI tool"
    license: "GPL-3.0"
    formats:
      - deb
      - rpm
      - archlinux
    bindir: /usr/bin
    section: utils
    priority: optional
    contents:
      - src: ./LICENSE
        dst: /usr/share/licenses/hydectl/LICENSE
      - src: ./README.md
        dst: /usr/share/doc/hydectl/README.md

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
