name: Release
on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: GoReleaser Tag Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: goreleaser/goreleaser-action@v6.3.0
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: GoReleaser Master Snapshot
        if: github.ref == 'refs/heads/master'
        uses: goreleaser/goreleaser-action@v6.3.0
        with:
          version: latest
          args: release --snapshot --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
