name: Release
on:
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: GoReleaser Action
        uses: goreleaser/goreleaser-action@v6.3.0

        with:
          version: latest
