name: Go Release

on:
  push:
    tags:
      - "v*"
    branches:
      - master

permissions:
  contents: write
  packages: write
  issues: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: useblacksmith/setup-go@v6
        with:
          go-version: "1.24.1"

      - name: Set nightly version
        if: github.ref == 'refs/heads/master'
        run: |
          echo "NIGHTLY_VERSION=nightly-$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --config .github/.goreleaser.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_CURRENT_TAG: master